=== nathanswanson/SM-Backend/src/server_manager/resources/template.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "name",
        "image"
    ],
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the template."
        },
        "image": {
            "type": "string",
            "description": "The name of the Docker image to use for the container."
        },
        "tags": {
            "type": "array",
            "description": "Additional Tags for the Docker image. defaults to 'latest'.",
            "items": {
                "type": "string"
            }
        },
        "description": {
            "type": "string",
            "description": "A brief description of the template."
        },
        "resource": {
            "type": "object",
            "description": "Minimum resource requirements/allocated for the container.",
            "properties": {
                "cpu": {
                    "type": "number",
                    "minimum": 1,
                    "maximum": 4,
                    "default": 2,
                    "description": "The number of CPU cores allocated to the container."
                },
                "memory": {
                    "type": "string",
                    "pattern": "^[0-9]+[KMG]?$",
                    "default": "1G",
                    "description": "The amount of memory allocated to the container, e.g., '2G' for 2 gigabytes."
                }
            }
        },
        "env": {
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "type": "string"
                    },
                    {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                ]
            }
        },
        "extra_args": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ]
        }
    }
}

=== nathanswanson/SM-Backend/src/server_manager/templates/minecraft_java_8.json
{
    "name": "Minecraft",
    "description": "tes",
    "image": "itzg/minecraft-server",
    "tags": [
        "java8",
        "latest"
    ],
    "resource": {
        "memory": "2G",
        "cpu": 2
    },
    "env": [
        "MODRINTH_MODPACK",
        {
            "TYPE": "VANILLA"
        },
        {
            "EULA": "TRUE"
        }
    ],
    "extra_args": [
        ""
    ]
}

=== nathanswanson/SM-Backend/src/server_manager/resources/string.json
{
    "name": "string",
    "image": "string",
    "tags": [
        "string"
    ],
    "description": "string",
    "resource": {
        "cpu": 2.0,
        "memory": "1G"
    },
    "env": [
        "string",
        {
            "additionalProp1": "string",
            "additionalProp2": "string",
            "additionalProp3": "string"
        }
    ],
    "extra_args": "string"
}
